name: Ingwer
version: ${project.version}
main: de.bentzin.ingwer.IngwerPlugin
api-version: 1.15
authors: [Ture Bentzin]
description: Ingwer ${ingwer.status}
#For Ingwer Vault (i am searching for a stealth solution for this)
softdepend:
  - vault